config/routes.rb
  resources :cocktails do
    resources :ingredients, except: [:index, :show]
  end

  root to: 'cocktails#index'

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  attr_accessible :name, :notes
  validates :name,  presence: true
  has_many :ingredients, dependent: :destroy
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :cocktail_id, :ingredient
  validates :ingredient,  presence: true
  belongs_to :cocktail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  # GET /cocktails
  # GET /cocktails.json
  def index
    @cocktails = Cocktail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cocktails }
    end
  end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
    @cocktail = Cocktail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cocktail }
    end
  end

  # GET /cocktails/new
  # GET /cocktails/new.json
  def new
    @cocktail = Cocktail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cocktail }
    end
  end

  # GET /cocktails/1/edit
  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(params[:cocktail])

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render json: @cocktail, status: :created, location: @cocktail }
      else
        format.html { render action: "new" }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cocktails/1
  # PUT /cocktails/1.json
  def update
    @cocktail = Cocktail.find(params[:id])
    @ingredient = @cocktail.ingredients.find(params[:id])
    
    respond_to do |format|
      if @cocktail.update_attributes(params[:cocktail])
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy

    respond_to do |format|
      format.html { redirect_to cocktails_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @cocktail = Cocktail.find(params[:id])
    @ingredient = Ingredient.find(params[:id])
    @ingredient.edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = @cocktail.ingredients.create(params[:ingredient])
    redirect_to cocktail_path(@cocktail)
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @cocktail = Cocktail.find(params[:id])
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to cocktail_path(@cocktail), notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = @cocktail.ingredients.find(params[:id])
    @ingredient.destroy
    redirect_to cocktail_path(@cocktail)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= form_for(@cocktail) do |f| %>
  <% if @cocktail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cocktail.errors.count, "error") %> prohibited this cocktail from being saved:</h2>

      <ul>
      <% @cocktail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

<h2>Ingredients</h2>
<ul>
<% @cocktail.ingredients.each do |ingredient| %>
  <li>
    <%= ingredient.ingredient %>
     <%= link_to 'Delete', [ingredient.cocktail, ingredient], :method => :delete, :data => { :confirm => 'Are you sure?' } %>
  </li>
<% end %>
</ul>
<h3>Add an ingredient</h3>
<%= render "ingredients/form" %>


  <div class="field">
    <%= f.label :Directions %><br />
    <%= f.text_area :notes %>
  </div>  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing cocktail</h1>

<%= render 'form' %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<h1>Listing cocktails</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cocktails.each do |cocktail| %>
  <tr>
    <td><%= cocktail.name %></td>
    <td><%= link_to 'Show recipe', cocktail %></td>
    <td><%= link_to 'Edit', edit_cocktail_path(cocktail) %></td>
    <td><%= link_to 'Delete', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cocktail', new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>New cocktail</h1>

<%= render 'form' %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @cocktail.name %></h1>

<h2>Ingredients</h2>
<ul>
<% @cocktail.ingredients.each do |ingredient| %>
  <li>
    <%= ingredient.ingredient %>
<<<<<<< HEAD
    <%= link_to 'Edit', edit_cocktail_ingredient_path(ingredient),:class => 'btn' %>
     <%= link_to 'Delete', [ingredient.cocktail, ingredient], :class => 'btn', :method => :delete, :data => { :confirm => 'Are you sure?' } %>
=======
     <%= link_to 'Edit', [ingredient], :method => :edit %>
     <%= link_to 'Delete', [ingredient.cocktail, ingredient], :method => :delete, :data => { :confirm => 'Are you sure?' } %>
>>>>>>> cb7bab47c1614b896255d6bbdd14858ef2c2d019
  </li>
<% end %>
</ul>

<h3>Add an ingredient</h3>
<%= render "ingredients/form" %>

<h2>Directions</h2>
<p><%= @cocktail.notes %></p>


<%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
<%= link_to 'Back', cocktails_path %>

app/views/ingredients/_form.html.erb
<%= form_for([@cocktail, @cocktail.ingredients.build]) do |f| %>
<%-# form_for([@cocktail, @ingredient]) do |f| # this is karl's line - doesn't work on my version%>
<p>
    <%= f.text_field :ingredient %>
  </p>

  <p>
    <%= f.submit "Add", :class => 'btn'%>
  </p>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', cocktail_path(@cocktail) %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <tr>
    <th>Ingredient</th>
    <th>Cocktail</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= ingredient.ingredient %></td>
    <td><%= ingredient.cocktail_id %></td>
    <td><%= link_to 'Show', ingredient %></td>
    <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
    <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ingredient:</b>
  <%= @ingredient.ingredient %>
</p>

<p>
  <b>Cocktail:</b>
  <%= @ingredient.cocktail_id %>
</p>


<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CocktailSimple3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container">
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
 </div>
</body>
</html>